name: Deployment Pipeline

on: 
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Docker
              uses: docker/setup-buildx-action@v3

            - name: Build and deploy fastAPI app
              run: |
                docker build -t fastapi-app .
                docker run -d -p 8000:8000 fastapi-app
