name: Deployment Pipeline

on: 
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

            - name: Deploy to Server
              run: |
                ssh -o StrictHostKeyChecking=no devm@${{ secrets.SERVER_IP }} << 'EOF'

                # Ensure required packages are installed
                #apt-get update
                #apt-get install -y git docker.io nginx
                
                #Ensure app is cloned
                if [ ! -d "/fastapi-book-project" ]; then
                    git clone https://github.com/Elijah57/fastapi-book-project.git
                fi
                
                cd fastapi-book-project/
                git pull origin main

                # Build and run project in a container
                sudo docker build -t fastapi-app .
                sudo docker stop fastapi-app || true
                sudo docker rm fastapi-app || true
                sudo docker run -d --name fastapi-app -p 8000:8000 fastapi-app
                
                
                # Set up Nginx configuration
                echo "🔧 Setting up nginx configurations"
                sudo cat <<NGINX_CONF > /etc/nginx/sites-available/fastapi.conf
                server {
                    listen 80;
                    server_name ${{ secrets.SERVER_IP }};

                    location / {
                        proxy_pass http://127.0.0.1:8000;
                        proxy_set_header Host \$host;
                        proxy_set_header X-Real-IP \$remote_addr;
                        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto \$scheme;
                    }
                }
                NGINX_CONF

                sudo ln -sf /etc/nginx/sites-available/fastapi.conf /etc/nginx/sites-enabled/
                sudo systemctl restart nginx

                echo "✅ Deployment Successful!"
                EOF

        
          
